# Generated by Django 4.2.2 on 2023-06-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerSignup',
            fields=[
                ('sellerid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
