# Generated by Django 4.2.2 on 2023-06-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_sellersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('productprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productcolor', models.CharField(max_length=100)),
                ('productcategory', models.CharField(max_length=100)),
                ('productdescription', models.TextField()),
                ('productimage', models.FileField(upload_to='product_images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='register.sellersignup')),
            ],
        ),
    ]
