# Generated by Django 4.2.2 on 2023-06-15 14:03

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=255)),
                ('productprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productcolor', models.CharField(max_length=100)),
                ('productcategory', models.CharField(max_length=100)),
                ('productdescription', models.TextField()),
                ('productimage', models.FileField(blank=True, null=True, upload_to=api.models.product_images)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.sellersignup')),
            ],
        ),
    ]
