# Generated by Django 4.2.2 on 2023-06-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
