# Generated by Django 4.2.2 on 2023-06-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_order_cart_order_cartid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
