# Generated by Django 4.2.2 on 2023-06-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
